# Task 5: Web Data Extraction & Analysis

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "https://books.toscrape.com/"
response = requests.get(url)

In [3]:
response.status_code

200

In [4]:
soup = BeautifulSoup(response.text, "html.parser")

In [5]:
books = soup.find_all('article', class_='product_pod')
len(books)

20

In [6]:
books[0].h3.a['title']

'A Light in the Attic'

In [7]:
books[0].find('p', class_='price_color').text

'Â£51.77'

In [8]:
books[0].find('p', class_='star-rating')['class'][1]

'Three'

In [9]:
titles = [book.h3.a['title'] for book in books]

In [10]:
prices = [book.find('p', class_='price_color').text for book in books]

In [11]:
ratings = [book.find('p', class_='star-rating')['class'][1] for book in books]

In [12]:
scraped_data = pd.DataFrame({
    'Book_Title': titles,
    'Price': prices,
    'Rating': ratings
})

In [13]:
scraped_data.head()

                              Book_Title    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

In [14]:
scraped_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Book_Title  20 non-null     object
 1   Price       20 non-null     object
 2   Rating      20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [15]:
scraped_data.isnull().sum()

Book_Title    0
Price         0
Rating        0
dtype: int64

In [16]:
scraped_data.duplicated().sum()

np.int64(0)

In [18]:
scraped_data['Price'] = (
    scraped_data['Price']
    .str.replace('Â£', '', regex=False)
    .str.replace('£', '', regex=False)
    .astype(float)
)

In [19]:
rating_map = {
    'One': 1,
    'Two': 2,
    'Three': 3,
    'Four': 4,
    'Five': 5
}

scraped_data['Rating'] = scraped_data['Rating'].map(rating_map)

In [20]:
scraped_data.head()

                              Book_Title  Price  Rating
0                   A Light in the Attic  51.77       3
1                     Tipping the Velvet  53.74       1
2                             Soumission  50.10       1
3                          Sharp Objects  47.82       4
4  Sapiens: A Brief History of Humankind  54.23       5

In [21]:
scraped_data['Price'].describe()

count    20.000000
mean     38.048500
std      15.135231
min      13.990000
25%      22.637500
50%      41.380000
75%      51.865000
max      57.250000
Name: Price, dtype: float64

In [22]:
scraped_data['Price'].mean()

np.float64(38.048500000000004)

In [23]:
scraped_data.loc[scraped_data['Price'].idxmax()]

Book_Title    Our Band Could Be Your Life: Scenes from the A...
Price                                                     57.25
Rating                                                        3
Name: 15, dtype: object

In [24]:
scraped_data['Rating'].value_counts().sort_index()

Rating
1    6
2    3
3    3
4    4
5    4
Name: count, dtype: int64

In [25]:
scraped_data.to_csv('scraped_books_data.csv', index=False)